# -*- coding: utf-8 -*-
"""LVADSUSR137_Abhishek_Iyer_B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auCLAm_NNzPbxuqTiV_CtF8FkFNdRRYp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler,StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, recall_score, f1_score, precision_score, r2_score,mean_squared_error, confusion_matrix

df = pd.read_csv("/content/booking.csv")
df.head()

df.isna().sum()

#There are two columns with null values. We'll fill them up with mean value
df['average price'] = df['average price'].fillna(np.mean(df['average price']))
room_type_mode = df['room type'].mode()[0]
df['room type'] = df['room type'].fillna(room_type_mode)

df.isna().sum()

df.info()

#Encoding categorical variables
df.drop(columns = 'Booking_ID', inplace = True)
df.drop(columns = 'date of reservation', inplace = True)
df.drop_duplicates(inplace = True)
df_enc = df.drop(columns = 'booking status')
df_enc = pd.get_dummies(df)
df_enc.head()

df_enc.drop_duplicates(inplace = True)

X = df_enc
y = df['booking status']
y = y.apply(lambda x: 1 if x=='Not_Canceled' else 0)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(accuracy_score(y_test, y_pred))

y_test

y_pred

from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred))

recall_score(y_test,y_pred)

f1_score(y_pred, y_test)

confusion_matrix(y_test, y_pred)

